matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic
    - os: osx
      osx_image: xcode8.3
      language: objective-c
branches:
  only:
    - master
    - development
    - travis-linux
before_install:
  - ./.travis/before_install.sh
script:
  - ./.travis/install.sh
