language: objective-c
osx_image: xcode8.2
branches:
  only:
    - master
    - development
before_install:
  - brew update
  - brew install libsodium
  - brew install opus
script: swift build -Xlinker -L/usr/local/lib -Xlinker -lopus -Xcc -I/usr/local/include
